paths:
  origin_data: 'data/feature_extraction/origin/videos'
  origin_annotations: 'data/feature_extraction/origin/annotations'
  training_data: 'data/feature_extraction/training/videos'
  training_annotations: 'data/feature_extraction/training/annotations'
  validation_data: 'data/feature_extraction/validation/videos'
  validation_annotations: 'data/feature_extraction/validation/annotations'
  testing_data: 'data/feature_extraction/testing/videos'
  testing_annotations: 'data/feature_extraction/testing/annotations'
  results_path: 'results/'
  phase_annotations_path: 'data/phase_detection/annotations'
  phase_videos_path: "data/phase_detection/videos"

