origin_path:
  data: "data/videos"
  annotations: "data/annotations"
training_path:
  data: "training/videos"
  annotations: "training/annotations"
validation_path:
  data: "validation/videos"
  annotations: "validation/annotations"
file_formats:
  data_type: ".mp4"
  annotation_type: ".txt"
settings:
  frame_rate: 25
  colour_chanel: "BGR"
