data_path: "data"
training_path: "training"
validation_path: "validation"
data_type: ".mp4"
annotation_type: ".txt"
frame_rate: 25
model_width: 256
model_height: 256
colour_chanel: "BGR"
training_split: 90