origin_path:
  data: "/media/rho66/KINGSTON/SENG402/data/videos"
  annotations: "/media/rho66/KINGSTON/SENG402/data/annotations"
training_path:
  data: "/media/rho66/KINGSTON/SENG402/training/videos"
  annotations: "/media/rho66/KINGSTON/SENG402/training/annotations"
validation_path:
  data: "/media/rho66/KINGSTON/SENG402/validation/videos"
  annotations: "/media/rho66/KINGSTON/SENG402/validation/annotations"
file_formats:
  data_type: ".mp4"
  annotation_type: ".txt"
settings:
  frame_rate: 25
  colour_chanel: "BGR"
